import importlib
import importlib.util
import inspect
import pkgutil
import time
from pathlib import Path

from unified_model_caller.errors import InvalidServiceError
from unified_model_caller.services.base import BaseService


def _load_services() -> dict[str, type[BaseService]]:
    registry: dict[str, type[BaseService]] = {}
    services_path = Path(__file__).parent / "services"
    for _, module_name, _ in pkgutil.iter_modules([str(services_path)]):
        if module_name == "base":
            continue
        module = importlib.import_module(f"unified_model_caller.services.{module_name}")
        for _, cls in inspect.getmembers(module, inspect.isclass):
            if issubclass(cls, BaseService) and cls is not BaseService:
                name = cls("").get_name().lower()
                registry[name] = cls
    return registry


_SERVICES: dict[str, type[BaseService]] = _load_services()


class LLMCaller:
    """
    A unified caller for various Large Language Model (LLM) APIs.

    Dynamically discovers available services from the `services/` directory.
    Adding a new service requires only creating a new file there with a class
    that inherits from BaseService.
    """

    def __init__(self, service: str, model: str, api_key: str = ""):
        service_key = service.lower()
        if service_key not in _SERVICES:
            raise InvalidServiceError(f"'{service}' is not a valid service. Available: {list(_SERVICES.keys())}")
        self.model = model
        self._service: BaseService = _SERVICES[service_key](api_key)

    def wait_cooldown(self) -> None:
        """Waits the amount of time required by the service to respect rate limits."""
        time.sleep(self._service.service_cooldown() / 1000)

    def call(self, prompt: str) -> str:
        """
        Sends a prompt to the configured LLM and returns the response.

        Args:
            prompt (str): The input text to send to the model.

        Returns:
            str: The text generated by the model.
        """
        try:
            return self._service.call(self.model, prompt)
        except Exception as e:
            print(f"An error occurred while calling the {self._service.get_name()} API: {e}")
            raise e
